on:
  pull_request:
    branches:
      - main

jobs:
  wilco:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Pr checks

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: postgres
          SECRET_KEY: secret
          POSTGRES_DB: anythink-market
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out project
        uses: actions/checkout@v2

      - name: Use Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.13"

      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Setup Node for Wilco Checks
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Start application servers
        run: docker-compose up -d

      - name: Wait for servers to be ready
        run: sleep 10

      - name: Wilco checks
        id: Wilco
        uses: trywilco/actions@main
        with:
          engine: ${{ secrets.WILCO_ENGINE_URL }}
